<?php

namespace Database\Seeders;

use App\Models\Produk;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $produk = [
            'Astertrin',
            'Absina',
            'Acrobat 50 wp',
            'Alamo',
            'Aminovol',
            'Amistar Top',
            'Ammate',
            'Anda Extra-k',
            'Andahipo',
            'Andavit',
            'Antracol',
            'Aristick',
            'Arrivo',
            'Avidor',
            'Barctocyn',
            'Besgrime X',
            'Besramil 35 wp',
            'Besvidar 25 wp',
            'Bionasa',
            'Blastgone 75 wp',
            'Bom up',
            'Bosh Top',
            'Brood Plus 77 wp',
            'Cabrio Top',
            'Cakra Buana',
            'Calarise',
            'Cozene',
            'Crowen',
            'Curacron',
            'Danaquat',
            'De Besttan',
            'Dithane m-45',
            'Dupont Lannate 25 wp',
            'Em 4',
            'Emarvel',
            'Et-Prorice',
            'Everstick',
            'Fastac',
            'Fetrilon',
            'Filia',
            'Flash Gordon',
            'Fujiwan',
            'Furadan',
            'Gandasil',
            'Gempur',
            'Hantu',
            'Heksa', 
            'Primasid Mapan P-05',
            'Humustar',
            'Kayabas',
            'Kempo',
            'Kick Off',
            'KNO Merah',
            'Larvin',
            'Lindomin',
            'Marshal',
            'Matador',
            'Mega',
            'Megathane',
            'Mestafen',
            'Mipcindo',
            'Mipcinta',
            'Naga',
            'Newtonik',
            'Nominee',
            'Noxone',
            'NPK',
            'Octave',
            'Preza',
            'Prime Plus',
            'KNO Putih',
            'Rampart',
            'Regent',
            'Remazole',
            'Rennate',
            'Ridomil Gold',
            'Roundup',
            'Sampurna',
            'Sankil',
            'Sanmex',
            'Score',
            'Serbuk Ajaib',
            'Sidacron',
            'Sidametrin',
            'Sinaclorin',
            'Spgro',
            'Starmex',
            'Sprnasa',
            'Susi 80',
            'Swallow',
            'Tabas',
            'Taft',
            'Termikon',
            'T-Fordi',
            'Ti-Gold',
            'Topsida',
            'Topsin-m 70 wp',
            'Ultron',
            'Virtako',
            'X-tra Kcl',
            'Zenus 276 SL',
            'Latern',
            'Hibrida',
            'Padjajaran',
            'Pocnasa',
            'Premium Quality',
            'Riestas',
            'Spontan',
        ];

        $kategori = [
           'Insektisida',
           'Insektisida',
            'Fungisida',
            'Insektisida',
            'Pupuk',
            'Fungisida',
            'Insektisida',
            'Pupuk',
            'Insektisida',
            'Fungisida',
            'Fungisida',
            'Pestisida',
            'Insektisida',
            'Insektisida',
            'Fungisida',
            'Insektisida',
            'Fungisida',
            'Insektisida',
            'Herbisida',
            'Fungisida',
            'Herbisida',
            'Pupuk',
            'Herbisida',
            'Fungisida',
            'Benih',
            'Herbisida',
            'Fungisida',
            'Insektisida',
            'Insektisida',
            'Herbisida',
            'Pestisida',
            'Fungisida',
            'Insektisida',
            'Pupuk',
            'Insektisida',
            'Herbisida',
            'Insektisida',
            'Insektisida',
            'Pupuk',
            'Fungisida',
            'Insektisida',
            'Fungisida',
           'Insektisida',
            'Pupuk',
            'Herbisida',
            'Pupuk',
            'Fungisida',
           'Benih', 
           ' Pupuk',
            'Herbisida',
            'Insektisida',
            'Insektisida',
            'Pupuk',
            'Insektisida',
            'Herbisida',
            'Insektisida',
            'Insektisida',
            'Pupuk',
            'Fungisida',
            'Insektisida',
            'Insektisida',
            'Insektisida',
            'Insektisida',
            'Pupuk',
            'Herbisida',
            'Herbisida',
            'Pupuk',
            'Fungisida',
            'Insektisida',
            'Pestisida',
            'Pupuk',
            'Fungisida',
            'Insektisida',
            'Fungisida',
            'Insektisida',
            'Fungisida',
            'Herbisida',
            'Pupuk',
            'Insektisida',
            'Insektisida',
            'Fungisida',
            'Pupuk',
            'Insektisida',
            'Insektisida',
            'Insektisida',
            'Pupuk',
            'Insektisida',
            'Pupuk',
            'Fungisida',
            'Pupuk',
            'Herbisida',
            'Fungisida',
            'Insektisida',
            'Herbisida',
            'Herbisida',
            'Fungisida',
            'Fungisida',
            'Herbisida',
            'Insektisida',
            'Pupuk',
            'Herbisida',
            'Herbisida',
            'Benih',
            'Benih Padi',
            'Pupuk',
            'Benih Padi',
            'Herbisida',
            'Insektisida',
 
        ];

        $deskripsi = [
            'Efektif untuk membasmi ulat api dan ulat kantong pada tanaman kelapa sawit.',
                'untuk mengendalikan hama ulat grayak pada tanaman bawang merah.',
                'berfungsi untuk mengendalikan penyakit pada tanaman yang disebabkan oleh jamur, seperti penyakit busuk daun',
                'untuk mengendalikan hama wereng coklat, wereng hijau, dan wereng punggung putih pada padi',
                'meningkatkan pertumbuhan dan perkembangan tanaman, mengatasi kekurangan unsur hara makro dan mikro pada tanaman',
                'untuk mengendalikan penyakit pada tanaman bawang merah, cabai, jagung, jarak, ',
                'efektif mengendalikan hama tanaman kacang-kacangan dan padi yaitu penggerek polong dan Hama Putih Palsu. ',
                'mengandung kalium, zpt, juga trace element serta ada anti jamurnya.',
                'untuk mengendalikan hama penggerek batang dan wereng coklat pada tanaman padi',
                'untuk mempercepat pertumbuhan tanaman cabe, padi, kacang-kacangan',
                'sangat efektif dalam menghambat, membunuh dan melindungi dari penyakit jamur',
                'bahan perekat dan perata pestisida yang dapat menembus jaringan tanaman secara langsung',
                'berfungsi untuk mengendalikan berbagai jenis hama pada tanaman cabai, bawang merah, jagung',
                'untuk mengendalikan hama wereng coklat pada tanaman padi dan kutu daun',
                'untuk mengobati hama bakteri dan jamur pada tanaman. ',
                'untuk mengendalikan hama grayak kutu daun pada tanaman cabai.',
                'digunakan untuk mengendalikan penyakit busuk daun, busuk buah pada tanaman.', 
                'bermanfaat mengendalikan hama pengganggu pada tanaman budidaya seperti Wereng hijau atau coklat', 
                'untuk mengendalikan gulma berdaun lebar dan tipis  pada tanaman perkebunan (karet, kelapa sawit dan tanaman singkong)',
                'untuk mengendalikan penyakit blast atau kresek pada tanaman padi.',
                'merupakan pupuk pemacu pertumbuhan akar dan daun sehingga mempercepat proses pertumbuhan pada tanaman',
                'efektif mengendalikan lebih banyak gulma pada tanaman padi. Dapat disemprot maupun tabur bersama dengan pupuk',
                'zat pengatur tumbuh tanaman untuk mengendalikan penyakit pada tanaman bawang merah, cabai, kacang tanah',
                'Padi Genjah tahan hama dan penyakit, bermalay panjang, bulir lonjong besar, anakan banyak hingga 65',
                'mampu mengendalikan gulma sasaran tanpa meracuni tanaman pokoknya.',
                'untuk mengendalikan penyakit penting yang disebabkan oleh jamur pada pertanaman cabai, karet dan kentang.',
                'untuk mengendalikan hama dalam jangka waktu yang lama mampu mengendalikan hama dari tanaman padi',
                'dapat digunakan untuk mengendalikan hampir semua jenis hama pada tanaman.',
                'untuk mengendalikan gulma berdaun lebar dan gulma golongan rumput.',
                'untuk mengendalikan hama pada tambak udang windu dan ikan bandeng.',
                'untuk mengendalikan penyakit jamur yang menyerang pada pertanian, perkebunan dan pembibitan.',
                'sangat efektif dan cepat mengendalikan serangan hama penggerek buah pada tomat hingga ke telur serangga.',
                'diaplikasikan sebagai inokulan untuk meningkatkan keanekaragaman dan populasi mikroorganisme di dalam tanah dan tanaman',
                'mengendalikan hama ulat grayak, ulat penggulung daun, pada tanaman bawang merah,jagung serta untuk mengendalikan penggerek batang padi',
                'untuk mengendalikan gulma pada budidaya tanaman padi',
                'Membantu meratakan/melekatkan pestisida permukaan daun yang berbulu yang sukar untuk ditembus air.',
                'mampu membasmi semua jenis hama dari hama sejenis ulat grayak, ulat bulu, kutu putih, bahkan belalang yang mengganggu tanaman',
                'untuk memudahkan penyerapan dan translokasi keseluruh jaringan Tanaman dan sangat sesuai digunakan untuk semua jenis Tanaman',
                'untuk mengendalikan penyakit yang disebabkan oleh jamur cercospora pada tanaman',
                'memaksimalkan kinerja pestisida agar bisa menembus jaringan kulit sehingga secara maksimal cepat mati untuk yang sulit dijangkau seperti ulat sundep',
                'untuk mengendalikan penyakit blas pada tanaman padi, bercak daun',
                'untuk mengendalikan beragam jenis hama, terutama hama penggerek batang, cacing, ulat, dan semut.',
                'bekerja dengan cara merangsang pertumbuhan atau keluarnya bunga serta pembentukan buah pada tanaman buah',
                'pembasmi rumput dan gulma herbisida.',
                'membasmi hama tanaman terbuat dari bahan organik aman bagi makhluk hidup',
                'untuk mengendalikan penyakit jamur cercospora pada tanaman.',
                'mapan P-05 cocok untuk daerah irigasi teknis',
                'berfungsi sebagai penyubur tanah.',
                'mampu membrantas gulma dan rumput liar didalam tanaman jagung',
                'dapat mengendalikan hama penggerek batang padi yang berada pada tempat yang tersembunyi.',
                'Insektisida Obat Pembasmi Hama Kutu dan Thrips.',
                'KNO3 Merah cocok untuk fase vegetatif (pertumbuhan awal tanaman sampai menjelang pembungaan).',
                'Digunakan Untuk Mengendalikan Hama Pada Tanaman Bawang Merah,Cabai,Jagung',
                'pengendalikan gulma daun lebar.',
                'untuk mengendalikan hama dengan aplikasi benih pada bawang, jagung, kedelai, padi',
                'untuk mengendalikan hama perusak daun, ulat grayak, wereng, walang',
                'Bahan perekat dan perata untuk insektisida fungisida herbisida',
                'untuk mengendalikan penyakit busuk daun',
                'untuk mengendalikan hama penggerek polong, Bisa juga untuk membunuh serangga dalam rumah.',
                'untuk mengendalikan hama pada tanaman cabai, jagung, kakao, keledai dan padi',
                'dapat membentuk suspensi dalam air untuk mengendalikan hama-hama penting pada tanaman padi, jagung',
                'sebagai pengendali hama wereng pada tanaman seperti padi dan sayuran ',
                'untuk merangsang pertumbuhan dan kesuburan semua jenis tanaman',
                'mengendalikan beberapa kelompok gulma semusim, tanaman tahunan, alang-alang, dan gulma berdaun ',
                'untuk mengendalikan aneka jenis gulma, juga rumput teki pada tanaman jagung',
                'membantu pertumbuhan tanaman agar berkembang secara maksimal.',
                'untuk mengendalikan penyakit layu fusarium pada tanaman bawang.',
                'untuk mengendalikan hama pada tanaman tomat, cabai, bawang merah, kubis, kacang panjang, mentimun.',
                'untuk mengurangi pertumbuhan tunas samping pada tanaman',
                'Merangsang dan mempercepat pertumbuhan akar tanaman.Menyuburkan dan memperkuat jaringan tanaman',
                'untuk mengendalikan penyakit bercak kering pada budidaya tanaman kentang.',
                'digunakan untuk mengendalikan hama pada tanaman kedelai, jagung dan padi serta sebagai ZPT pada Jagung.',
                'untuk mengendalikan penyakit pada tanaman padi, bawang merah, kedelai dan mangga',
                'berfungsi membasmi berbagai jenis ulat, lalat buah, dan berbagai jenis kutu',
                'untuk mengendalikan penyakit busuk buah, busuk daun dan busuk batang pada tanaman pertanian.',
                'obat pembasmi rumput liar, alang-alang, atau gulma yang umumnya tumbuh di tanah yang masih belum diolah, di kebun maupun pekarangan.',
                'mampu mendorong pertumbuhan tanaman sehingga dapat tumbuh lebih cepat',
                'untuk mengendalikan hama ulat grayak pada tanaman bawang merah.',
                'Mengendalikan hama yg menyebabkan puret dan keriting pada daun.',
                'Mengoptimalkan pembungaan sehingga malai keluar serempak.',
                'berfungsi menghijaukan daun padi, meningkatkan anakan padi dan mengobati penyakit tanaman padi',
                'berbentuk pekatan yang dapat diemulsikan  untuk mengendalikan hama pada tanaman',
                'Pengendali hama Tanaman, seperti ulat tanaman, wereng, lalat buah ',
                'untuk mengendalikan hama ulat grayak pada pertanaman bawang merah',
                'pupuk khusus untuk menpercepat pertumbuhan tanaman',
                'untuk mengendalikan serangga seperti tunggu, nyamuk sawah, kaper, ulat, penggerek batang, perusak daun pada tanaman sayuran',
                'untuk memperbaiki tanah yg secara fisik sdh tergolong rusak',
                'berfungsi untuk meningkatkan pertumbuhan tanaman,meningkatkan ketahanan tanaman terhadap serangan hama dan penyakit.',
                'untuk memberikan rangsangan agar tanaman memiliki daya tahan terhadap serangan hama dan penyakit, terutama kutu merah dan jamur.',
                'membasmi rumput atau gulma didalam tanaman padi, tanpa ada efek samping pada padinya, sehingga mengurangi biaya produksi tanam',
                'membasmi penyakit hawar daun pada jagung dan penyakit bercak coklat pada padi',
                'digunakan untuk membasmi hama rayap kayu dan rayap tanah',
                'untuk mengendalikan gulma berdaun lebar',
                'untuk membasmi gulma daun lebar dan tunas gulma pada tanaman padi.',
                'untuk mengendalikan penyakit blas pada pertanaman padi.',
                'Mengendalikan penyakit busuk buah pada tanaman buah-buahan dan sayur, melindungi tanaman tembakau dari penyakit bercak daun',
                'untuk mengendalikan gulma umum pada tanaman padi.',
                'untuk mengendalikan hama pada tanaman bawang merah, cabai, dan padi sawah. Mengendalikan Ulat Penggerek Batang (Sundep)',
                'Membantu merangsang tanaman dalam penyusunan unsur hara dengan memperbaiki sistem perakaran tanaman dan merangsang keluarnya akar baru',
                'untuk mengendalikan gulma pada pertanaman kelapa sawit dan jagung',
                'untuk mengendalikan gulma berdaun lebar dan gulma berdaun sempit pada tanaman karet ',
                'produk persilangan antara dua tetua padi yang berbeda secara genetik.',
                'berumur genjah atau sekitar 105 hari setelah semai,',
                'untuk mempercepat pertumbuhan tanaman, mencegah kerontokan bunga dan buah',
                'Umur tanaman 115-125 hari, Jumlah bulir per malai 300-350, Tahan terhadap wereng coklat, virus tungro,',
                'Anti rayap, Penyiraman pada tanah dengan dosis 5 liter larutan per meter persegi.',
                'untuk mengatasi Wereng Coklat, Penggerek batang, belalang',
                'untuk mengatasi Wereng Coklat, Penggerek batang, belalang',
        ];

        $harga = [
            '25000',
            '85000',
            '12000',
            '55000',
            '35000',
            '55000',
            '65000',
            '35000',
            '30000',
            '10000',
            '38000',
            '18000',
            '12000',
            '35000',
            '40000',
            '325000',
            '35000',
            '35000',
            '105000',
            '15000',
            '100000',
            '35000',
            '12000',
            '5000',
            '70000',
            '85000',
            '65000',
            '20000',
            '35000',
            '45000',
            '15000',
            '35000',
            '5000',
            '20000',
            '75000',
            '110000',
            '25000',
            '15000',
            '25000',
            '55000',
            '40000',
            '22000',
            '22000',
            '12000',
            '105000',
            '40000',
            '75000',
            '110000',
            '45000',
            '95000',
            '22000',
            '300000',
            '53000',
            '12000',
            '28000',
            '8000',
            '45000',
            '65000',
            '35000',
            '35000',
            '35000',
            '15000',
            '16000',
            '20000',
            '75000',
            '28000',
            '20000',
            '85000',
            '125000',
            '75000',
            '58000',
            '12000',
            '18000',
            '35000',
            '35000',
            '35000',
            '120000',
            '10000',
            '48000',
            '90000',
            '58000',
            '12000',
            '20000',
            '14000',
            '70000',
            '38000',
            '90000',
            '65000',
            '65000',
            '38000',
            '110000',
            '70000',
            '12000',
            '25000',
            '18000',
            '25000',
            '20000',
            '10000',
            '12000',
            '25000',
            '90000',
            '85000',
            '70000',
            '70000',
            '65000',
            '70000',
            '55000',
            '30000'
        ];

        $stok= [
            '85',
            '12',
            '55',
            '5',
            '5',
            '5',
            '35',
            '30',
            '10',
            '38',
            '18',
            '12',
            '25',
            '35',
            '40',
            '32',
            '35',
            '35',
            '10',
            '15',
            '10',
            '35',
            '12',
            '5',
            '70',
            '85',
            '65',
            '20',
            '35',
            '45',
            '15',
            '35',
            '5',
            '20',
            '75',
            '11',
            '25',
            '15',
            '25',
            '55',
            '40',
            '22',
            '22',
            '12',
            '100',
            '40',
            '75',
            '70',
            '45',
            '95',
            '22',
            '30',
            '53',
            '58',
            '12',
            '28',
            '8',
            '45',
            '65',
            '35',
            '35',
            '35',
            '15',
            '16',
            '20',
            '75',
            '28',
            '20',
            '85',
            '70',
            '65',
            '70',
            '12',
            '11',
            '75',
            '12',
            '18',
            '35',
            '35',
            '35',
            '12',
            '10',
            '48',
            '90',
            '58',
            '12',
            '20',
            '14',
            '70',
            '38',
            '65',
            '90',
            '65',
            '38',
            '11',
            '70',
            '12',
            '25',
            '18',
            '25',
            '20',
            '10',
            '12',
            '25',
            '90',
            '70',
            '55',
            '30'
        ];
    
        foreach ($produk as $key => $value){
            Produk::create([    
            'nama_produk' => $produk[$key],
            'kategori' => $kategori[$key],
            'deskripsi' => $deskripsi[$key],
            'harga' => $harga[$key],
            'stok' => $stok[$key],
            'gambar' => 'gambar ('.$key.').png'
            ]);
        }
    }
}
